# Generated by Django 3.2.9 on 2021-11-15 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211114_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catergory',
            name='catergory',
        ),
        migrations.AddField(
            model_name='catergory',
            name='name',
            field=models.CharField(default='Other', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.CharField(choices=[('Mens', 'Men'), ('Woman', 'Woman'), ('Kids', 'Kids')], default=1, max_length=6),
        ),
    ]
