# Generated by Django 3.2.9 on 2021-11-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catergory_sub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catergory',
            field=models.CharField(choices=[('Mens', 'Men'), ('Woman', 'Woman'), ('Kids', 'Kids')], default='', max_length=10),
        ),
    ]
